spring:
  application:
    version: 1.0
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        default_schema: default_weather
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

city:
  latitude: "53.90060110"
  longitude: "27.55897200"

integration:
  weather-api:
    url: "https://weatherapi-com.p.rapidapi.com"
    key: "e850b19bfcmshfe7aea336ee5198p1bb5e3jsn2fcd74fc3057"
    host: "weatherapi-com.p.rapidapi.com"
    delay: 300000

